//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citas()
        {
            this.facturacion = new HashSet<facturacion>();
        }
    
        public int id_cita { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
        public int id_servicio { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual servicios servicios { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturacion> facturacion { get; set; }
    }
}
