//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public int id_factura { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int id_cita { get; set; }
        public int id_producto { get; set; }
        public int cantidad_producto { get; set; }
        public decimal total_servicio { get; set; }
        public decimal total_producto { get; set; }
        public decimal total { get; set; }
    
        public virtual citas citas { get; set; }
        public virtual inventario inventario { get; set; }
    }
}
