//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public int id_factura { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int id_cita { get; set; }
        public int id_producto { get; set; }
        public int cantidad_producto { get; set; }
        public decimal total_servicio { get; set; }
        public decimal total_producto { get; set; }
        public decimal total { get; set; }
    
        public virtual citas citas { get; set; }
        public virtual inventario inventario { get; set; }
    }
}
