//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carwashEntities : DbContext
    {
        public carwashEntities()
            : base("name=carwashEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<categoria_inventario> categoria_inventario { get; set; }
        public virtual DbSet<categoria_servicios> categoria_servicios { get; set; }
        public virtual DbSet<citas> citas { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<facturacion> facturacion { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
