//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string first_surname { get; set; }
        public string second_surname { get; set; }
        public int phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string token_recovery { get; set; }
        public int role_id { get; set; }
        public bool isActive { get; set; }
        public string activation_token { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
