//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {

        [Key]
        public int userId { get; set; }

        [Required]
        public string password { get; set; }

        [Required]
        public string token_recovery { get; set; }

        [Required]
        public Nullable<System.DateTime> date_created { get; set; }

        [Required]
        public string email { get; set; }

        [Required]
        public int id_rol { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
